// apps/svelte/src/routes/entertainment/+page.svelte
<script lang="ts">
	import DkrhCrudPage
		from "$lib/components/DkrhCrudPage.svelte";

	const columns = [
		{
			key: "entryTitle",

			label:
				"Entry Title",
		},

		{
			key: "statusPublication",

			label:
				"Publication",
		},

		{
			key: "statusDl",

			label:
				"Download",
		},
	];

	const fields = [
		{
			key: "entryTitle",

			label:
				"Entry Title",

			type:
				"text",
		},

		{
			key:
				"statusPublication",

			label:
				"Publication Status",

			type:
				"text",
		},

		{
			key:
				"statusDl",

			label:
				"Download Status",

			type:
				"text",
		},
	];
</script>

<DkrhCrudPage
	title="Entertainment Tracker"

	apiBase="/api/h-entertainment-tracker"

	searchPlaceholder="Search entertainment..."

	{columns}

	{fields}

	deleteLabelColumn="entryTitle"
/>

// apps/_old_react (not use)/src/pages/entertainment/index.tsx
import { DkrhCrudPage } from "@/components/dkrhCrudPage";

export default function EntertainmentPage() {

    return (
        <DkrhCrudPage
            title="Entertainment"
            apiBase="/api/h-entertainment-tracker"
            searchPlaceholder="Search entertainment..."
            deleteLabelColumn="entryTitle"
            columns={[
                {
                    key: "typeId",
                    label: "Type",
                    show: "name",
                },
                {
                    key: "entryTitle",
                    label: "Title"
                },
                {
                    key: "lastMark",
                    label: "Last Read"
                },
                {
                    key: "linkDL",
                    label: "Link DL"
                },
                {
                    key: "statusDL",
                    label: "Last DL"
                },
            ]}
            fields={[
				{
					key: "typeId",
					label: "Type",
					type: "dropdown",
                    api: "/api/entertainment-types",
                    valueField: "id",
                    labelField: "name",
				},
                {
                    key: "entryTitle",
                    label: "Title"
                },
                {
                    key: "lastMark",
                    label: "Last Read"
                },
                {
                    key: "linkDL",
                    label: "Link DL"
                },
                {
                    key: "statusDL",
                    label: "Last DL"
                },
            ]}
        />
    );
}
