// _trash/_old_react (not use)/src/components/dkrhCrudModal.tsx
import { useEffect, useState } from "react";

import DkrhInput from "@/components/dkrhInput";
import { apiFetch, getAPIURL } from "./const";

export function DkrhCrudModal({
	title,
	data = {},
	fields,
	apiBase,
	onClose
}: any) {

	const [form, setForm] = useState(data);
	const [resolvedFields, setResolvedFields] = useState(fields);

	useEffect(() => {
		async function loadFields() {
			const newFields = await Promise.all(
				fields.map(async (field: any) => {

					if (field.options)
						return field;

					if (field.type !== "dropdown" || !field.api)
						return field;

					const res = await apiFetch(
						getAPIURL(field.api)
					);

					const data = await res.json();

					return {
						...field,
						options: data.map((item: any) => ({
							value: item[field.valueField ?? "id"],
							label: item[field.labelField ?? "name"],
						})),
					};
				})
			);

			setResolvedFields(newFields);
		}

		loadFields();
	}, [fields]);

	async function save() {

		const method =
			data.id
				? "PUT"
				: "POST";

		const url =
			data.id
				? `${apiBase}/${data.id}`
				: apiBase;

		await apiFetch(url, {
			method,
			headers: {
				"Content-Type":
					"application/json"
			},
			body: JSON.stringify(form)
		});

		onClose();
	}

	return (

		<div
			className="
				fixed
				inset-0
				bg-black/70
				flex
				items-center
				justify-center
				z-50
			"
		>

			<div
				className="
					bg-zinc-900
					p-6
					rounded-xl
					w-[700px]
					border
					border-zinc-700
				"
			>

				<h2
					className="
						text-2xl
						font-bold
						mb-4
					"
				>
					{
						data.id
							? `Edit ${title}`
							: `Add ${title}`
					}
				</h2>

				<div
					className="
						grid
						grid-cols-2
						gap-4
					"
				>
					{resolvedFields.map((f: any) => {
						const { key, ...props } = f;

						return (
							<DkrhInput
								key={key}
								{...props}
								value={form[key] ?? ""}
								onChange={(v: any) =>
									setForm({
										...form,
										[key]: v,
									})
								}
							/>
						);
					})}
				</div>

				<div
					className="
						flex
						justify-center
						gap-3
						mt-6
					"
				>

					<button
						onClick={onClose}

						className="
							bg-zinc-700
							hover:bg-zinc-600
							px-4
							py-2
							rounded
						"
					>
						Cancel
					</button>

					<button
						onClick={save}

						className="
							bg-blue-600
							hover:bg-blue-500
							px-4
							py-2
							rounded
						"
					>
						Save
					</button>

				</div>

			</div>

		</div>
	);
}

// apps/svelte/src/lib/components/DkrhCrudModal.svelte
<script lang="ts">
	import {
		apiFetch,
	} from "$lib/api";

	let {
		title,

		data,

		apiBase,

		fields,

		onClose,
	}: {
		title: string;

		data: any;

		apiBase: string;

		fields: any[];

		onClose: () => void;
	} = $props();

	let form = $state<any>({});

    $effect(() => {
        form = {
            ...data,
        };
    });
	let saving =
		$state(false);

	let error =
		$state("");

	async function submit() {
		saving = true;

		error = "";

		try {
			const isEdit =
				Boolean(form.id);

			const url =
				isEdit
					? `${apiBase}/${form.id}`
					: apiBase;

			await apiFetch(
				url,
				{
					method:
						isEdit
							? "PUT"
							: "POST",

					headers: {
						"Content-Type":
							"application/json",
					},

					body:
						JSON.stringify(
							form
						),
				}
			);

			onClose();
		}
		catch (err: any) {
			error =
				err.message ??
				"Failed to save.";
		}
		finally {
			saving = false;
		}
	}
</script>

<div
	class="
		fixed
		inset-0
		z-50
		bg-black/70
		flex
		items-center
		justify-center
		p-4
	"
>
	<div
		class="
			bg-zinc-900
			border
			border-zinc-700
			rounded-lg
			w-full
			max-w-lg
			max-h-[90vh]
			overflow-auto
			p-6
		"
	>
		<h2
			class="
				text-xl
				font-bold
				mb-4
			"
		>
			{form.id
				? `Edit ${title}`
				: `Add ${title}`}
		</h2>

		<div
			class="
				space-y-4
			"
		>
			{#each fields as field}

				<div>

					<label
	                    for={field.key}
						class="
							block
							mb-1
							text-sm
						"
					>
						{field.label}
					</label>

					{#if field.type === "textarea"}

						<textarea
                            id={field.key}
							value={
								form[
									field.key
								] ?? ""
							}

							oninput={(event) =>
								form[
									field.key
								] =
									event
										.currentTarget
										.value
							}

							class="
								w-full
								bg-zinc-950
								border
								border-zinc-700
								rounded
								p-3
							"
						></textarea>

					{:else}

						<input
                            id={field.key}
							type={
								field.type ??
								"text"
							}

							value={
								form[
									field.key
								] ?? ""
							}

							oninput={(event) =>
								form[
									field.key
								] =
									event
										.currentTarget
										.value
							}

							class="
								w-full
								bg-zinc-950
								border
								border-zinc-700
								rounded
								p-3
							"
						/>

					{/if}

				</div>

			{/each}
		</div>

		{#if error}

			<div
				class="
					mt-4
					text-red-400
				"
			>
				{error}
			</div>

		{/if}

		<div
			class="
				flex
				justify-end
				gap-2
				mt-6
			"
		>
			<button
				onclick={onClose}

				class="
					bg-zinc-700
					px-4
					py-2
					rounded
				"
			>
				Cancel
			</button>

			<button
				onclick={submit}

				disabled={saving}

				class="
					bg-blue-600
					px-4
					py-2
					rounded
					disabled:opacity-50
				"
			>
				{saving
					? "Saving..."
					: "Save"}
			</button>
		</div>
	</div>
</div>
